### ISSUE TITLE
[Feature Request] Variable to load output file in Notepad++

### ISSUE THREAD

**Issue by fabiorzfreitas** [npp-plugins/pork2sausage#13]
When progOutput is set and replaceSelection=false, it would be useful to add a variable to load the output file.

It would be useful e. g. when one is using Notepad++ to build simple commands and don't actually want the selection to be overwritten, but still want to immediately view the output. More specifically, it would have been great when I used RegEx in Notepad++ to turn the output from some data fetched via REST API into a curl command for a new fetch.

**Comment by donho** [comment]
You can add the following line into `progCmd`:
`C:\Program Files (x86)\Notepad++\notepad++.exe <my output file path>`

I tested with the following content in `pork2Sausage.ini`:
```
[CaptureOnly1024Bytes]
progPath=C:\Windows\System32\cmd.exe
progCmd=cmd.exe /c "type C:\sources\notepad-plus-plus\LICENSE > c:\tmp\output & "C:\Program Files (x86)\Notepad++\notepad++.exe" c:\tmp\output"
workDir=C:\Windows\System32
replaceSelection=false
```
It does work fine to me.
