### ISSUE TITLE
pork2Sausage.ini” is not present.

### ISSUE THREAD

**Issue by marceepoonu** [npp-plugins/pork2sausage#17]
See my issue at this url:
        https://community.notepad-plus-plus.org/topic/24566/notepad-says-it-cannot-find-the/3?_=1687965416263
I previously posted a question and got some help, “https://community.notepad-plus-plus.org/topic/24060/how-to-add-or-install-pork2sausage-to-notepad”, that I was not able to figure out how to use that help to fix the Pork2Sausage installation problem.
So, I uninstalled and reinstalled Notepad++.
Now, when I open Notepad++, I get a message telling me that “C:\Users\marc\AppData\Roaming\Notepad++\plugins\Config\pork2Sausage.ini” is not present.
I did a search for files I thought are significant and found the following files:

C:\Program Files\Notepad++\plugins\pork2sausage\pork2sausage.dll
C:\Program Files\Notepad++\plugins\pork2sausage\Config\pork2Sausage.ini
So, the pork2Sausage.ini file and the pork2sausage.dll are both present on my PC.

The page “https://npp-user-manual.org/docs/plugins/#install-plugin-manually” does not explain how to fix a plugin installation that did not get done right, which I think is what happened in my case.

Marc

**### SOLUTION:**
Peter Jones' gave me a solution (at the same URL) and I'm sharing his solution here so that you folks fix this problem so that other people don't have to struggle.

Here's peter's solution
[PeterJones](https://community.notepad-plus-plus.org/user/peterjones)  [Jun 12, 2023, 8:23 PM](https://community.notepad-plus-plus.org/post/87023)
[@Marc-Hankin](https://community.notepad-plus-plus.org/uid/12465) ,

I ran some experiments. It had nothing to do with version, nor with whether it was local-config or AppData config, like I was originally thinking when I asked for the Debug Info.

Apparently, that plugin does not automatically install its config file when it gets installed, and instead just stores it in a subdirectory of the plugin’s installation directory.

You will want to exit the Notepad++ application; then copy C:\Program Files\Notepad++\plugins\pork2sausage\Config\pork2Sausage.ini to C:\Users\marc\AppData\Roaming\Notepad++\plugins\Config\pork2Sausage.ini; then restart Notepad++ – the error message should stop at this point, and Plugins > Pork to Sausage will now list some example converters, as well as a command to edit the User Commands. (Please note: unless you have an ancient version of java where Don had them, and have a working directory already created under Don’s personal user name, the default pork2sausage.ini commands will not work for you.)

Other readers of this topic: since your username is likely not marc, you should copy the source ini to %AppData%\Notepad++\plugins\Config\pork2Sausage.ini, which uses the Windows OS Envioronment Variable %AppData% [🛈](https://community.notepad-plus-plus.org/topic/15740/faq-desk-what-is-appdata) to find the right hiearchy based on the active username and settings.

**Comment by Flaflo** [comment]
thanks a lot!
