### ISSUE TITLE
Consistency in naming of this plug-in.

### ISSUE THREAD

**Issue by NudeSpoons** [npp-plugins/pork2sausage#2]
There are inconsistencies in the names used in reference to this plugin, as follows:

- the GitHub project is named `pork2sausage`
- the readme.txt file refers to it as `Pork to Sausage`
- in GitHub, both versions 1.0 and 2.0 use the name `Pork2Sausage`
- in GitHub, version 2.1 calls it `Pork to Sausage`
- the drop-down Plugins menu in Notepad++ uses the label `Pork to Sausage`
- in Notepad++, the Plugin Manager lists `Pork2Sausage` in the Available tab
- in Notepad++, the Plugin Manager lists `Pork to Sausage` in the Installed tab

Can these references (and any others I have missed) all be reconciled to a single consistent name?  I suggest using `Pork to Sausage` for all references that are visible to the end-user, as this provides the most clarity.

**Comment by donho** [comment]
Its binary name is `pork2sausage.dll`
its short name is `Pork2Sausage`
its full name is `Pork to Sausage`
I don't see why the need to change all that.
