### ISSUE TITLE
Plugin appears to be both Available and Installed.

### ISSUE THREAD

**Issue by NudeSpoons** [npp-plugins/pork2sausage#3]
I have installed version 2.1 of this plugin in Notepad++ version 7.5.4 (64-bit).
When I check using Plugin Manager version 1.4.11, listed under the **Installed** tab there is a row with the following details:
- Plugin: **Pork to Sausage**
- Category: _blank_
- Installed Version: **2.1**
- Stability: _blank_

and when I highlight the row or tick its check-box, this is displayed in the message box below:
```
Unknown plugin - please let us know about this plugin on the forums
Stability: 
```
If I then switch to the **Available** tab in Plugin Manager, the plugin is also listed here, as follows:
- Plugin: **Pork2Sausage**
- Category: **others**
- Available Version: **2.1**
- Stability: **Good**

and highlighting the row or checking its box gives this in the message area:
```
Transforms selected text to through a transformer (a console program which takes inputs then generates output). Up to 20 transformers can be defined
Author: Don Ho
Source: https://github.com/npp-plugins/pork2sausage
Latest update: 16 Sep 2016 Remove the dependecy issue
```
I'm not sure whether this is a Plugin Manager issue, but the difference in the names of the plugin between the two tabs in Plugin Manager is worth noting.

Also, note the typo in the message that displays on the **Available** tab in Plugin Manager:
`Transforms selected text to through ...` should be simply `Transforms selected text through ...`.

**Comment by chcg** [comment]
@NudeSpoons Seems @donho has modified the release package. Referenced for x64 is:

				<download>https://github.com/npp-plugins/pork2sausage/releases/download/v2.1/pork2sausage.2.1.bin.zip</download>

, but that one (single zip with 32 and 64 bit dlls) was removed, splitted for 32/64 bit and replaced with:

https://github.com/npp-plugins/pork2sausage/releases/download/v2.1/pork2sausage.2.1.bin.x64.zip

This also happens silently with the other plugins here under https://github.com/npp-plugins

**Comment by NudeSpoons** [comment]
Release package was updated.
