### ISSUE TITLE
feature request: allow pork to be empty

### ISSUE THREAD

**Issue by shawnkhall** [npp-plugins/pork2sausage#9]
Since N++ 7.6 TextFX isn't supported even in 32-bit and I would really like to be able to use the insert timestamps feature (like standard Notepad). It works...but requires me to create a selection first, which slows progress quite a bit.

Would you please enable Pork2Sausage to work without an active selection?

I could see using this for other system-state or diagnostic information as well where the "pork" is coming from outside Notepad++.

**Comment by donho** [comment]
Even Jesus needs the water for transforming into wine.
I will see what I can do about it.
